#!/usr/bin/env python3
"""Generate source-level IR that makes the real allocator spill divergent values."""
import argparse
from pathlib import Path


def generate(n):
    lines = ['// Generated by generate_high_pressure.py; no low IR or explicit spills.',
             '// Four lanes retain N independent integers across a divergent loop.',
             '// Input values are all 1. Active lanes 0/1 double; lanes 2/3 quadruple.',
             '// Mode 1 gives trip counts [4,3,2,1]; mode 0 gives [4,4,4,4].',
             '// Output residuals must all be zero, using exact integer arithmetic.']
    a = lines.append
    a(f'''kernel.def @pressure() {{
  %one = index.constant 1 : index
  %four = index.constant 4 : index
  kernel.launch.config workgroups(%one, %one, %one) workgroup_size(%four, %one, %one) : index
}} launch(%input: buffer, %output: buffer, %mode: buffer) {{
  %lane = kernel.workitem.id<x> : index
  %base = index.constant 0 : offset
  %iv = buffer.view %input[%base] : buffer -> view<{4*n}xi32>
  %ov = buffer.view %output[%base] : buffer -> view<{4*n}xi32>
  %stride = index.constant {n} : index
  %row = index.mul %lane, %stride : index
  %li = index.cast %lane : index to i32
  %four_i = scalar.constant 4 : i32
  %mode_view = buffer.view %mode[%base] : buffer -> view<1xi32>
  %flag = view.load %mode_view[0] : view<1xi32> -> i32
  %effective_lane = scalar.muli %li, %flag : i32
  %bound = scalar.subi %four_i, %effective_lane : i32
  %zero = scalar.constant 0 : i32
  %one_i = scalar.constant 1 : i32''')
    for j in range(n):
        a(f'  %j{j} = index.constant {j} : index\n  %ix{j} = index.add %row, %j{j} : index\n  %v{j} = view.load %iv[%ix{j}] : view<{4*n}xi32> -> i32')
    def names(prefix):
        return ', '.join(f'%{prefix}{j}' for j in range(n))
    types = ', '.join(['i32'] * n)
    all_types = 'i32, ' + types
    args = ', '.join(f'%x{j} = %v{j} : i32' for j in range(n))
    body_args = ', '.join(f'%b{j}: i32' for j in range(n))
    a(f'''  %iterations, {names('r')} = scf.while(%i = %zero : i32, {args}) -> ({all_types}) {{
    %go = scalar.cmpi slt, %i, %bound : i32
    scf.condition %go, %i, {names('x')} : i1, {all_types}
  }} do(%k: i32, {body_args}) {{
    %next = scalar.addi %k, %one_i : i32
    %two = scalar.constant 2 : i32
    %branch = scalar.cmpi slt, %li, %two : i32
    {names('y')} = scf.if %branch -> ({types}) {{''')
    for j in range(n):
        a(f'      %a{j} = scalar.addi %b{j}, %b{(j+1)%n} : i32')
    a(f"      scf.yield {names('a')} : {types}\n    }} else {{")
    for j in range(n):
        a(f'      %c{j} = scalar.addi %b{j}, %b{(j+1)%n} : i32\n      %d{j} = scalar.addi %c{j}, %c{j} : i32')
    a(f'''      scf.yield {names('d')} : {types}
    }}
    scf.yield %next, {names('y')} : {all_types}
  }}
  %tw = scalar.constant 2 : i32
  %fast = scalar.cmpi slt, %li, %tw : i32
  %double_bound = scalar.addi %bound, %bound : i32
  %exponent = scf.select %fast, %bound, %double_bound : i32
  %expected = scalar.shli %one_i, %exponent : i32''')
    for j in range(n):
        a(f'  %diff{j} = scalar.subi %r{j}, %expected : i32\n  view.store %diff{j}, %ov[%ix{j}] : i32, view<{4*n}xi32>')
    a('  kernel.return\n}')
    for case, mode in [('divergent_pressure', 1), ('uniform_trip_count', 0)]:
        a(f'''check.case @{case} {{
  %input = check.generate.fill value(1) : tensor<{4*n}xi32>
  %out = check.generate.fill value(-1) : tensor<{4*n}xi32>
  %expected = check.generate.fill value(0) : tensor<{4*n}xi32>
  %mode_value = check.generate.fill value({mode}) : tensor<1xi32>
  kernel.launch @pressure(%input, %out, %mode_value) : (tensor<{4*n}xi32>, tensor<{4*n}xi32>, tensor<1xi32>)
  check.expect.equal actual(%out) expected(%expected) : tensor<{4*n}xi32>
  check.return
}}''')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--width', type=int, default=170)
    parser.add_argument('--output', type=Path, default=Path(__file__).with_name('high-pressure.loom'))
    args = parser.parse_args()
    if args.width < 2:
        parser.error('--width must be at least 2')
    args.output.write_text(generate(args.width))
