#!/usr/bin/env python3
"""Derive an f32-only spill experiment from the maintained f64 reproducer."""
import argparse
import hashlib
from pathlib import Path
import re
import subprocess
import sys

HERE = Path(__file__).resolve().parent
# Skip comments, quoted text, identifiers, and hexadecimal/integer suffixes.
# In particular, hexadecimal hash constants must not be mistaken for decimals.
TOKENS = re.compile(
    r'(?P<opaque>//[^\n]*|/\*.*?\*/|"(?:\\.|[^"\\])*"|'
    r"'(?:\\.|[^'\\])*'|[A-Za-z_]\w*|0[xX][0-9a-fA-F]+[uUlL]*|\d+[uUlL]+)"
    r'|(?P<real>(?:\d+\.\d*|\.\d+)(?:[eE][+-]?\d+)?[fFlL]?'
    r'|\d+[eE][+-]?\d+[fFlL]?)',
    re.DOTALL,
)


def float_literals(text):
    def convert(match):
        if match.group('real') is None:
            return match.group()
        return match.group().rstrip('fFlL') + 'f'
    return TOKENS.sub(convert, text)


def replace_once(text, old, new):
    assert text.count(old) == 1, (old, text.count(old))
    return text.replace(old, new)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    subprocess.run([sys.executable, str(HERE / 'generate.py'), '--check'], check=True)
    output = HERE / 'f32'
    if not args.check:
        output.mkdir(exist_ok=True)
    for name in ('support.h', 'reproducer.cpp', 'integrate.inc'):
        source = (HERE / name).read_text()
        text = source
        if name == 'support.h':
            text = replace_once(text, 'using Real = double;', 'using Real = float;')
            text = replace_once(text, '#define MAX_DOUBLE __DBL_MAX__',
                                '#define MAX_REAL __FLT_MAX__')
            text = replace_once(text,
                'unsigned long long bits = __builtin_bit_cast(unsigned long long, x);\n'
                '    return (bits & 0x7ff0000000000000ULL) != 0x7ff0000000000000ULL;',
                'unsigned int bits = __builtin_bit_cast(unsigned int, x);\n'
                '    return (bits & 0x7f800000U) != 0x7f800000U;')
            text = replace_once(text,
                "// The host test uses the system's original double math. The Loom translation\n"
                '// retains f64 operations, without AFN/ARCP or any replacement approximation.',
                '// Spill experiment: all floating storage, literals, and math use f32.\n'
                '// Approximate math is a separate importer option, not implied by precision.')
        elif name == 'reproducer.cpp':
            text = replace_once(text, 'static_assert(sizeof(CellRecord) == 216);',
                                'static_assert(sizeof(CellRecord) == 136);')
            text = replace_once(text, 'static_assert(sizeof(ScratchRecord) == 4848);',
                                'static_assert(sizeof(ScratchRecord) == 2468);')
            text = text.replace('MAX_DOUBLE', 'MAX_REAL')
            # f32 has 24 significand bits. Avoid a u64-to-f32 conversion whose
            # current AMDGPU legalization uses an f64 intermediate.
            text = replace_once(text, 'const auto bits = splitmix64(seed) >> 11U;',
                                'const auto bits = static_cast<unsigned int>(splitmix64(seed) >> 40U);')
            text = replace_once(text, 'static_cast<Real>(1ULL << 53U)',
                                'static_cast<Real>(1U << 24U)')
            text = replace_once(text,
                '// Generated by generate.py from reference.cpp; do not hand edit.',
                '// Derived from the f64 reproducer; do not hand edit.')
        text = float_literals(text)
        digest = hashlib.sha256(source.encode()).hexdigest()
        # Keep the license first, and preserve existing source notices.
        first, rest = text.split('\n', 1)
        text = (first + '\n// Generated by ../generate_f32.py; do not hand edit.\n'
                f'// Parent {name} SHA256: {digest}\n' + rest)
        destination = output / name
        if args.check:
            if not destination.exists() or destination.read_text() != text:
                raise SystemExit(f'{destination} is stale; run {Path(__file__).name}')
        else:
            destination.write_text(text)
        print(f'{"Checked" if args.check else "Generated"} {destination.relative_to(HERE)}')


if __name__ == '__main__':
    main()
