#!/usr/bin/env python3
"""Specialize the pinned chemistry source; never rewrite floating expressions.

The checked-in output is ordinary C++. Run this script after editing the
translation rules, and --check in CI. Exact replacements fail on source drift.
"""
import argparse
import hashlib
from pathlib import Path
import re

HERE = Path(__file__).resolve().parent
SOURCE = (HERE / "reference.cpp").read_text()
SOURCE_SHA256 = '6c7ca23933b211980e831e8d2bfc4328245ab0e3c75f6b07a5e0ed40307843d0'
assert hashlib.sha256(SOURCE.encode()).hexdigest() == SOURCE_SHA256, (
    'reference.cpp changed: review every specialization rule before updating the pinned digest')


def body(name):
    match = re.search(r"\b" + re.escape(name) + r"\s*\([^;{]*\)\s*\{", SOURCE)
    if not match:
        raise ValueError(name)
    start = match.end()
    depth = 1
    end = start
    while depth:
        depth += (SOURCE[end] == "{") - (SOURCE[end] == "}")
        end += 1
    return SOURCE[start:end - 1]


def replace(text, old, new, count=1):
    assert text.count(old) == count, (old, text.count(old), count)
    return text.replace(old, new)


def common(text):
    text = text.replace("integrators::", "").replace("pc::", "")
    text = text.replace("std::size_t", "size_type").replace("std::uint64_t", "u64")
    text = text.replace("std::", "math::")
    text = re.sub(r"IntegratorResult::(\w+)", r"\1", text)
    # The source chemistry expressions use literal, one-based output indices.
    text = re.sub(r'\bX\((\d+)\)', lambda m: f'xn[{int(m[1])}]', text)
    text = re.sub(r'\bydot\((\d+)\)', lambda m: f'out[{int(m[1]) - 1}]', text)
    text = re.sub(r'\bjac\((\d+),(\d+)\)',
                  lambda m: f'out[{int(m[1]) - 1}][{int(m[2]) - 1}]', text)
    return text


parts = ['// SPDX-License-Identifier: BSD-3-Clause\n'
         '// Generated by generate.py from reference.cpp; do not hand edit.\n'
         '// Source SHA256: ' + hashlib.sha256(SOURCE.encode()).hexdigest() + '\n'
         '#include "support.h"\nnamespace chemistry {\n']


def emit(signature, text):
    parts.append("DEVICE " + signature + " {\n" + common(text) + "\n}\n")


# Extract all constants at their original precision.
for name in ['NumSpec', 'neqs', 'net_ienuc', 'default_redshift', 'grav_constant', 'pi',
             'tff_reduc', 'rtol_spec', 'atol_spec', 'rtol_energy', 'atol_energy',
             'perturbation_interval', 'perturbation_amplitude']:
    match = re.search(r'constexpr (?:integrators::)?(Real|int) ' + name + r' = ([^;]+);', SOURCE)
    assert match, name
    parts.append(f'constexpr {match[1]} {name} = {match[2]};\n')
parts.append('constexpr size_type N = 15;\n')
for name, code in [('SUCCESS', 1), ('BAD_INPUTS', -1), ('DT_UNDERFLOW', -2),
                   ('TOO_MANY_STEPS', -4), ('TOO_MUCH_ACCURACY_REQUESTED', -5),
                   ('LU_DECOMPOSITION_ERROR', -7)]:
    parts.append(f'constexpr int {name} = {code};\n')
coef = SOURCE[SOURCE.index('struct ROS2SCoefficients'):SOURCE.index('} // namespace detail', SOURCE.index('struct ROS2SCoefficients'))]
parts.append('namespace C {\n' + '\n'.join(re.findall(r'static (constexpr Real [^;]+;)', coef)) + '\n}\n')
parts.append('struct EosSums { Real sum_Abarinv; Real sum_gammasinv; Real gasconstant; };\n')
parts.append('struct IntegratorStats { u64 internal_steps; u64 rhs_calls; u64 jacobian_calls; '
             'u64 decompositions; u64 linear_solves; u64 accepted_steps; u64 rejected_steps; };\n')
parts.append('struct BurnRecord { Real rho; Real T; Real e; Real xn[14]; };\n')
parts.append('struct CellRecord { BurnRecord current; Real time; Real density_driver; '
             'int completed_steps; IntegratorStats stats; };\n')
parts.append('static_assert(sizeof(CellRecord) == 216);\n')

# Typed scratch-field schema: one element range per field, per cell.
real_fields = [('t', 1, '0.0'), ('tout', 1, '0.0'), ('dt', 1, '0.0'),
               ('y', 15, '0.0'), ('rtol_vec', 15, '0.0'), ('atol_vec', 15, '0.0'),
               ('uround', 1, '1.e-16'), ('fac_min', 1, '0.2'), ('fac_max', 1, '6.0'), ('safe', 1, '0.9')]
real_fields += [(n, 225 if n in ('fjac', 'e') else 15, '0.0')
                for n in ('ynew', 'ak1', 'ak2', 'work', 'fjac', 'e', 'dy')]
real_fields += [('burn', 17, '0.0'), ('mass', 14, '0.0')]
int_fields = [(n, 1, '0') for n in ('n_step', 'n_rhs', 'n_jac', 'n_accept', 'n_reject', 'n_decomp', 'n_solve')]
int_fields += [('max_steps', 1, '100000'), ('ip', 15, '0')]
parts.append('struct ScratchRecord {\n')
for kind, fields in [('Real', real_fields), ('int', int_fields)]:
    for name, count, _ in fields:
        if name == 'burn':
            declaration = 'BurnRecord burn'
        elif name in ('fjac', 'e'):
            declaration = f'{kind} {name}[15][15]'
        elif count == 1:
            declaration = f'{kind} {name}'
        else:
            declaration = f'{kind} {name}[{count}]'
        parts.append(f'  {declaration};\n')
parts.append('};\nstatic_assert(sizeof(ScratchRecord) == 4960);\n')
parts.append('struct BurnView { Real* rho; Real* T; Real* e; Real* xn; };\n')
parts.append('struct ScratchView {\n')
for name, _, _ in real_fields + int_fields:
    if name == 'burn':
        parts.append('  BurnView burn;\n')
    else:
        kind = 'int' if name in {field for field, _, _ in int_fields} else 'Real'
        parts.append(f'  {kind}* {name};\n')
parts.append('};\n')


def scratch_view_access(text):
    """Project a pointer-only view without changing source arithmetic."""
    for field in ('rho', 'T', 'e'):
        text = text.replace(f's->burn.{field}', f's.burn.{field}[0]')
    text = text.replace('s->burn.xn', 's.burn.xn')
    scalar_fields = {name for name, count, _ in real_fields + int_fields
                     if count == 1 and name != 'burn'}
    for name, _, _ in real_fields + int_fields:
        if name == 'burn':
            continue
        replacement = f's.{name}[0]' if name in scalar_fields else f's.{name}'
        text = re.sub(r'\bs->' + name + r'\b', replacement, text)
    assert not re.search(r'\bs->', text)
    return text


def flatten_matrix_access(text, names):
    for name in names:
        pattern = r'\b' + re.escape(name) + r'\[([^\[\]]+)\]\[([^\[\]]+)\]'
        text = re.sub(pattern, lambda m: f'{name}[matrix_index({m[1]}, {m[2]})]', text)
    return text


def scratch_view_initializer(local):
    fields = []
    for name, _, _ in real_fields + int_fields:
        if name == 'burn':
            if local:
                fields.append('{&burn_rho, &burn_T, &burn_e, burn_xn}')
            else:
                fields.append('{&s->burn.rho, &s->burn.T, &s->burn.e, s->burn.xn}')
        elif local:
            fields.append('&' + name if name in scalar_scratch_fields else name)
        else:
            fields.append('&s->' + name if name in scalar_scratch_fields else
                          ('&s->' + name + '[0][0]' if name in ('fjac', 'e') else 's->' + name))
    return '{' + ', '.join(fields) + '}'


scalar_scratch_fields = {name for name, count, _ in real_fields + int_fields
                         if count == 1 and name != 'burn'}
parts.append('DEVICE ScratchView scratch_view(ScratchRecord* s) {\n')
parts.append('  return ' + scratch_view_initializer(False) + ';\n}\n')
parts.append('DEVICE size_type matrix_index(size_type row, size_type column) {\n'
             '  size_type index = row * 15 + column;\n'
             '  __builtin_assume(index < 225);\n'
             '  return index;\n}\n')
for name in ('small_number_density_floor', 'species_mass', 'species_gamma'):
    emit('Real ' + name + ('(int n)' if name != 'small_number_density_floor' else '()'), body(name))
emit('Real density(const Real* xn)', replace(body('density'), 'xn.size()', 'NumSpec'))
eos = body('eos_sums_from_number_densities')
for n in ('n_A', 'k_B', 'm_p'):
    value = re.search(r'constexpr Real ' + n + r' = ([^;]+);', SOURCE)[1]
    eos = eos.replace('constants::' + n, value)
emit('EosSums eos_sums_from_number_densities(const Real* xn)', eos)
for name in ('eos_rt', 'eos_re'):
    routine = body(name).replace('state.xn', 'b->xn').replace('state.e', 'b->e').replace('state.T', 'b->T')
    emit('void ' + name + '(BurnRecord* b)', routine)
routine = body('eos_re').replace('state.xn', 'b.xn').replace('state.e', 'b.e[0]').replace('state.T', 'b.T[0]')
emit('void eos_re_view(BurnView b)', routine)
emit('void balance_charge(BurnRecord* b)', body('balance_charge').replace('state.xn', 'b->xn'))
normalize = replace(body('normalize_number_densities_to_density'), 'std::array<Real, NumSpec> mass_fractions{};', '')
normalize = normalize.replace('mass_fractions.size()', 'NumSpec').replace('state.xn', 'b->xn').replace('state.rho', 'b->rho')
emit('void normalize_number_densities_to_density(BurnRecord* b, Real* mass_fractions)', normalize)
emit('void floor_and_normalize_number_densities(BurnRecord* b, Real* mass)', '''
    for (int n = 0; n < NumSpec; ++n) {
        b->xn[n] = math::max(b->xn[n], small_number_density_floor());
    }
    normalize_number_densities_to_density(b, mass);
''')

# Preserve the generated arithmetic while translating its literal indices.


def shallow_conditionals(name, text):
    """Outline parenthesized ternaries, retaining lazy branch evaluation.

    All captured xN/T/z variables in these three generated routines are Real
    locals with no mutation during an expression. xn is a read-only pointer.
    auto return deduction preserves bool/int/Real conditional-expression types.
    Each helper contains just one ternary; no eager select or reassociation.
    """
    ordinal = 0
    while '?' in text:
        stack = []
        conditional_parents = set()
        found = None
        for pos, char in enumerate(text):
            if char == '(':
                stack.append(pos)
            elif char == '?':
                conditional_parents.add(stack[-1])
            elif char == ')':
                start = stack.pop()
                if start in conditional_parents:
                    found = start, pos + 1
                    break
        assert found, name
        start, end = found
        expression = text[start:end]
        assert expression.count('?') == 1
        captures = sorted(set(re.findall(r'\b(?:x\d+|T|z|xn)\b', expression)))
        if 'X(' in expression and 'xn' not in captures:
            captures.append('xn')
        helper = f'{name}_choice_{ordinal}'
        parameters = ', '.join(('const Real* ' if v == 'xn' else 'Real ') + v for v in captures)
        emit('auto ' + helper + '(' + parameters + ')', 'return ' + expression + ';')
        text = text[:start] + helper + '(' + ', '.join(captures) + ')' + text[end:]
        ordinal += 1
    return text


for name, signature in [('rhs_specie', 'void rhs_specie(Real temperature, Real* out, const Real* xn, Real z)'),
                         ('rhs_eint', 'Real rhs_eint(Real temperature, const Real* xn, Real z)'),
                         ('jac_nuc', 'void jac_nuc(Real temperature, Real* out, const Real* xn, Real z)')]:
    routine = shallow_conditionals(name, body(name).replace('state.T', 'temperature'))
    if name == 'jac_nuc':
        routine = flatten_matrix_access(common(routine), ('out',))
    emit(signature, routine)
# The source value-initializes burn_t, but species and e are overwritten here,
# and eos_re writes T. Only rho must retain its zero initialization.
emit('void burn_state_from_y(const Real* y, BurnRecord* b)', '''
    b->rho = 0.0;
    for (int n = 0; n < NumSpec; ++n) b->xn[n] = math::max(y[n], small_number_density_floor());
    b->e = y[NumSpec];
    eos_re(b);
''')
emit('void burn_state_from_y_view(const Real* y, BurnView b)', '''
    b.rho[0] = 0.0;
    for (int n = 0; n < NumSpec; ++n) b.xn[n] = math::max(y[n], small_number_density_floor());
    b.e[0] = y[NumSpec];
    eos_re_view(b);
''')
emit('void rhs(Real t, const Real* y, Real* out, ScratchView s)', '''
    BurnView b = s.burn;
    burn_state_from_y_view(y, b);
    rhs_specie(b.T[0], out, b.xn, default_redshift);
    Real edot = rhs_eint(b.T[0], b.xn, default_redshift);
    out[14] = edot;
''')
emit('void eval_jacobian(ScratchView s, Real x)', '''
    for (int n = 0; n < 15; ++n) for (int m = 0; m < 15; ++m) s.fjac[matrix_index(n, m)] = 0.0;
    BurnView b = s.burn;
    burn_state_from_y_view(s.y, b);
    jac_nuc(b.T[0], s.fjac, b.xn, default_redshift);
    s.n_jac[0] += 1;
''')
for name, signature, matrix in [('lu_decomposition', 'int lu_decomposition(Real* A, int* ipvt)', 'A'),
                                ('lu_solve', 'void lu_solve(const Real* LU, const int* ipvt, Real* x)', 'LU')]:
    routine = flatten_matrix_access(body(name), (matrix,))
    if name == 'lu_decomposition':
        routine = replace(routine, 'ipvt[k] = static_cast<int>(pivot_row);',
                          'ipvt[k] = static_cast<int>(pivot_row);\n            __builtin_assume(pivot_row < 15);')
    else:
        routine = replace(routine, 'const auto pivot_row = static_cast<size_type>(ipvt[k]);',
                          'const auto pivot_row = static_cast<size_type>(ipvt[k]);\n            __builtin_assume(pivot_row < 15);')
        routine = routine.replace('for (size_type j = k + 1; j < N; ++j) {',
                                  'for (size_type j = k + 1; j < N; ++j) {\n                __builtin_assume(j < 15);')
        routine = routine.replace('for (size_type j = 0; j < k; ++j) {',
                                  'for (size_type j = 0; j < k; ++j) {\n            __builtin_assume(j < 15);')
    emit(signature, routine)


def scratch_access(text):
    return re.sub(r'\bs\.(\w+)', r's->\1', text)


for name, signature in [('decompose', 'int decompose(ScratchView s, Real fac)'),
                         ('solve', 'void solve(ScratchView s, Real* ak)'),
                         ('error_norm', 'Real error_norm(ScratchView s)')]:
    text = scratch_access(body(name))
    text = text.replace('linalg::', '').replace('<N>', '')
    text = text.replace('atol_for(s, i)', 's->atol_vec[i]').replace('rtol_for(s, i)', 's->rtol_vec[i]')
    emit(signature, flatten_matrix_access(scratch_view_access(text), ('e', 'fjac')))

# Retain arithmetic in the original solver body. Only replace its control
# transfers and state representation; exact matching protects these edits.
text = scratch_access(body('integrate'))
text = replace(text, 'using C = detail::ROS2SCoefficients;', 'int result = SUCCESS;\n    bool done = false;')
text = text.replace('atol_for(s, i)', 's->atol_vec[i]').replace('rtol_for(s, i)', 's->rtol_vec[i]')
text = replace(text, 'return IntegratorResult::TOO_MUCH_ACCURACY_REQUESTED;', 'result = TOO_MUCH_ACCURACY_REQUESTED;\n                done = true;')
# The tolerance scan has no side effects; avoid evaluating any later elements
# after the first failing element, just as in the original.
first = text.index('for (size_type i = 0; i < N; ++i)')
text = text[:first] + text[first:].replace('i < N;', 'i < N && !done;', 1)
text = replace(text, 'for (size_type i = 0; i < N && !done; ++i) {',
               'for (size_type i = 0; i < N && !done; ++i) {\n            __builtin_assume(i < N);')
text = replace(text, '\n        const Real hmaxn', '\n        if (done) return result;\n        const Real hmaxn')
text = replace(text, 'for (;;) {', 'while (!done) {', count=2)
text = replace(text, 'return IntegratorResult::TOO_MANY_STEPS;', 'result = TOO_MANY_STEPS; done = true;')
text = replace(text, 'return IntegratorResult::DT_UNDERFLOW;', 'result = DT_UNDERFLOW; done = true;')
text = replace(text, 'return IntegratorResult::SUCCESS;', 'result = SUCCESS; done = true;')
text = replace(text, 'if (0.1 *', 'else if (0.1 *')
text = replace(text, 'if (last) {', 'else if (last) {')
text = replace(text, '\n            hopt = h;', '\n            if (!done) {\n            hopt = h;')
text = replace(text, 'eval_jacobian(s, x);', 'eval_jacobian(s, x);\n            bool retry = true;')
pos = text.index('bool retry = true;')
text = text[:pos] + text[pos:].replace('while (!done)', 'while (retry && !done)', 1)
text = replace(text, 'return IntegratorResult::LU_DECOMPOSITION_ERROR;',
               'result = LU_DECOMPOSITION_ERROR; done = true;\n                        continue;')
text = re.sub(r'\brhs\(([^;]+)\);', r'rhs(\1, s);', text)
text = replace(text, 'record_rhs(s, 3);', 's->n_rhs += 3;')
text = replace(text, 'record_step(s, n_step);', 's->n_step = n_step;')
text = replace(text, 'record_accept(s, n_accept);', 's->n_accept = n_accept;')
text = replace(text, 'record_reject(s);', 's->n_reject += 1;')
text = replace(text, 's->y = s->ynew;', 'for (size_type copy = 0; copy < N; ++copy) s->y[copy] = s->ynew[copy];')
text = replace(text, '                    break;\n                }', '                    retry = false;\n                } else {')
# Close the rejection else and outer continuation.
tail = '                if (n_accept >= 1) {\n                    s->n_reject += 1;\n                }\n            }\n        }\n    '
text = replace(text, tail, '                if (n_accept >= 1) {\n                    s->n_reject += 1;\n                }\n                }\n            }\n            }\n        }\n        return result;\n    ')
solver_control = '// SPDX-License-Identifier: BSD-3-Clause\n// Generated exact control rewrite; also tested with a singular-Jacobian fixture.\n'
solver_control += '#ifndef CHEM_EVAL_JACOBIAN\n#define CHEM_EVAL_JACOBIAN eval_jacobian\n#endif\n'
solver_control += '#ifndef CHEM_RHS\n#define CHEM_RHS rhs\n#endif\n'
text = text.replace('eval_jacobian(s, x);', 'CHEM_EVAL_JACOBIAN(s, x);')
text = text.replace('rhs(', 'CHEM_RHS(')
solver_control += 'DEVICE int integrate(ScratchView s) {\n' + flatten_matrix_access(scratch_view_access(common(text)), ('e', 'fjac')) + '\n}\n'
solver_control += '#undef CHEM_EVAL_JACOBIAN\n#undef CHEM_RHS\n'
# Reindent this small transformed block so the new control nesting is reviewable.
# There are no string literals, braced initializers, or comments containing braces.
solver_lines = []
depth = parens = 0
for line in solver_control.splitlines():
    line = line.strip()
    if line:
        leading_close = int(line.startswith('}'))
        solver_lines.append('    ' * (depth - leading_close + int(parens > 0)) + line)
        depth += line.count('{') - line.count('}')
        parens += line.count('(') - line.count(')')
    else:
        solver_lines.append('')
assert depth == parens == 0
solver_control = '\n'.join(solver_lines).rstrip() + '\n'
parts.append('#include "integrate.inc"\n')

initialization = []
for name, count, value in real_fields + int_fields:
    if name == 'burn':
        initialization.extend(f's.burn.{field}[0] = 0.0;' for field in ('rho', 'T', 'e'))
        initialization.append('for (int n = 0; n < 14; ++n) s.burn.xn[n] = 0.0;')
    elif name in ('fjac', 'e'):
        initialization.append(f'for (int n = 0; n < 15; ++n) for (int m = 0; m < 15; ++m) s.{name}[matrix_index(n, m)] = {value};')
    elif count == 1:
        initialization.append(f's.{name}[0] = {value};')
    else:
        initialization.append(f'for (int n = 0; n < {count}; ++n) s.{name}[n] = {value};')
emit('void initialize_solver(ScratchView s)', '\n'.join(initialization))
configure = body('configure_ros2s').replace('state.', 's.')
emit('void configure_ros2s(ScratchView s)', scratch_view_access(scratch_access(configure)))
burn = body('burn_ros2s')
burn = replace(burn, 'pc::eos_rt(state);', 'eos_rt(b);')
burn = replace(burn, 'Ros2sIntegrator integrator;\n    Ros2sIntegrator::State ros2s_state;', 'initialize_solver(s);')
burn = replace(burn, 'configure_ros2s(ros2s_state);', 'configure_ros2s(s);')
burn = burn.replace('ros2s_state.', 's.')
burn = replace(burn, 'integrator.integrate(ros2s_state)', 'integrate(s)')
burn = burn.replace('stats.', 'stats->')
burn = burn.replace('state.xn', 'b->xn').replace('state.e', 'b->e')
emit('int burn_ros2s(BurnRecord* b, Real dt, IntegratorStats* stats, ScratchView s)', scratch_view_access(scratch_access(burn)))
emit('u64 splitmix64(u64 value)', body('splitmix64'))
emit('Real perturbation_factor(int cell, int step)', body('perturbation_factor'))
emit('bool valid_positive(Real value)', body('valid_positive'))


def collapse(text, var):
    text = text.replace(var + '.current.xn', 'b->xn').replace(var + '.current.rho', 'b->rho')
    text = text.replace(var + '.density_driver', 'record->density_driver').replace(var + '.time', 'record->time')
    text = text.replace(var + '.completed_steps', 'record->completed_steps')
    text = text.replace(var + '.current', 'b').replace(var + '.stats', 'record->stats')
    text = text.replace('floor_and_normalize_number_densities(b)', 'floor_and_normalize_number_densities(b, mass)')
    return text


perturb = collapse(body('apply_perturbation'), 'collapse')
perturb = replace(perturb, 'for (auto& xn : b->xn) {\n        xn *= factor;', 'for (int n = 0; n < NumSpec; ++n) {\n        b->xn[n] *= factor;')
emit('void apply_perturbation(CellRecord* record, int cell, int step, bool enabled, Real* mass)',
     'BurnRecord* b = &record->current;\n' + perturb)
emit('Real collapse_timestep(const BurnRecord* b)', collapse(body('collapse_timestep'), 'collapse'))
local_scratch = []
for name, count, _ in real_fields + int_fields:
    kind = 'int' if name in {field for field, _, _ in int_fields} else 'Real'
    if name == 'burn':
        local_scratch += ['Real burn_rho;', 'Real burn_T;', 'Real burn_e;', 'Real burn_xn[14];']
    elif count == 1:
        local_scratch.append(f'{kind} {name};')
    else:
        local_scratch.append(f'{kind} {name}[{count}];')
local_scratch.append('ScratchView s = ' + scratch_view_initializer(True) + ';')
for name in ('prepare_grid_timestep_kernel', 'advance_collapse_gridwide_kernel'):
    text = body(name)
    text = replace(text, 'const int cell = blockIdx.x * blockDim.x + threadIdx.x;', '''
    const int cell = CELL_INDEX;
    ''')
    declarations = '\n'.join(local_scratch) if name.startswith('advance') else 'Real mass[14];'
    text = replace(text, 'CollapseState& state = cells[cell];',
                   'CellRecord* record = cells + cell;\nBurnRecord* b = &record->current;\n' + declarations)
    text = collapse(text, 'state')
    text = text.replace('apply_perturbation(state, cell, step, perturb)', 'apply_perturbation(record, cell, step, perturb, mass)')
    text = text.replace('collapse_timestep(state)', 'collapse_timestep(b)')
    text = text.replace('burn_ros2s(b, dt_grid, record->stats)', 'burn_ros2s(b, dt_grid, &record->stats, s)')
    text = text.replace('std::numeric_limits<integrators::Real>::max()', 'MAX_DOUBLE')
    text = text.replace('atomicCAS(', 'atomic_cas(').replace('atomicAdd(', 'atomic_add(')
    if name.startswith('advance'):
        text = replace(text, 'for (auto& xn : b->xn) {\n        xn *= density_ratio;', 'for (int n = 0; n < NumSpec; ++n) {\n        b->xn[n] *= density_ratio;')
        extra = 'Real next_grid_time, Real dt_grid, int* integrated_count'
    else:
        extra = 'Real grid_time, int step, bool perturb, Real* dt_candidates'
    parts.append('KERNEL void ' + name + '(CellRecord* cells, int num_cells, int completed_global_steps, ' + extra + ', int* failure_code CELL_PARAMETER) {\n' + common(text) + '\n}\n')
parts.append('} // namespace chemistry\n')

parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
reference_kernels = ['// SPDX-License-Identifier: BSD-3-Clause\n// Generated original kernel bodies for serial-lane differential testing.\n']
for name in ('prepare_grid_timestep_kernel', 'advance_collapse_gridwide_kernel'):
    start = SOURCE.index('__global__ void ' + name)
    end = SOURCE.index('{', start)
    signature = SOURCE[start:end].replace('__global__ void ' + name, 'void reference_' + name)
    signature = signature.rstrip()[:-1] + ', int cell_index)'
    text = body(name).replace('blockIdx.x * blockDim.x + threadIdx.x', 'cell_index')
    text = text.replace('atomicCAS(', 'chemistry::atomic_cas(').replace('atomicAdd(', 'chemistry::atomic_add(')
    reference_kernels.append(signature + '{' + text + '}\n')
for name, content in [('reproducer.cpp', ''.join(parts)),
                      ('reference_kernels.inc', ''.join(reference_kernels)),
                      ('integrate.inc', solver_control)]:
    if name == 'reproducer.cpp':
        assert not re.search(r'\b(?:X|ydot|jac)\(', content), 'untranslated chemistry index'
    path = HERE / name
    content = '\n'.join(line.rstrip() for line in content.splitlines()) + '\n'
    if args.check:
        assert path.read_text() == content, f'{name} is stale; run generate.py'
    else:
        path.write_text(content)
if args.check:
    assert not (HERE / 'layout.h').exists(), 'layout.h is obsolete'
