# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//loom/build_tools/bazel:build_defs.bzl", "loom_cc_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

loom_cc_library(
    name = "help",
    srcs = ["help.c"],
    hdrs = ["help.h"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/tooling:flags",
    ],
)

loom_cc_library(
    name = "loomc_options",
    srcs = ["loomc_options.c"],
    hdrs = ["loomc_options.h"],
    deps = [
        "//loom/binding/c:loomc",
        "//loom/src/loom/sanitizer:options",
        "//loom/src/loom/tooling/config",
        "//runtime/src/iree/base",
    ],
)

loom_cc_library(
    name = "loomc_result",
    srcs = ["loomc_result.c"],
    hdrs = ["loomc_result.h"],
    deps = [
        "//loom/binding/c:loomc",
        "//runtime/src/iree/base",
    ],
)

loom_cc_library(
    name = "loomc_diagnostic_json",
    srcs = ["loomc_diagnostic_json.c"],
    hdrs = ["loomc_diagnostic_json.h"],
    deps = [
        "//loom/binding/c:loomc",
        "//loom/src/loom/error:error_defs",
        "//loom/src/loom/util:json",
        "//loom/src/loom/util:stream",
        "//runtime/src/iree/base",
    ],
)
